### ISSUE TITLE
Create a mobile compatible version of the blog

### ISSUE THREAD

**Issue by malikpiara** [hotscope/blog#2]
This is a priority. The blog needs to be readable on the small screens so we can get our first leads.

**Comment by malikpiara** [comment]
@hacdias @ulissesferreira @fabiofcferreira: You clearly have more experience and I need your help here. Trying to make the blog mobile friendly and I don't know where to start. Here's a test page: https://blog.hotscope.io/page-2/

Would you be so kind to guide me into the right direction and resources? 🙏

**Comment by hacdias** [comment]
Hmm...

![image](https://user-images.githubusercontent.com/5447088/60128357-5b9fef80-978a-11e9-9e26-77c503775013.png)

An interesting post: https://css-tricks.com/look-ma-no-media-queries-responsive-layouts-using-css-grid/. Although I'd recommend to use media queries for now and flex boxes.

Old but gold: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by malikpiara** [comment]
Thank you! Vou dar uma vista de olhos!
